/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class duinoServerFrontend_Main */

#ifndef _Included_duinoServerFrontend_Main
#define _Included_duinoServerFrontend_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     duinoServerFrontend_Main
 * Method:    passInstruction
 * Signature: (Ljava/lang/String;I[BI)I
 */
JNIEXPORT jint JNICALL Java_duinoServerFrontend_Main_passInstruction
  (JNIEnv *, jclass, jstring, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
